---
server_url: https://tailscale.example.com

listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false
noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.50.0.0/16
  v6: fd7a:115c:a1e0:5050::/64

derp:
  server:
    enabled: true
    region_id: 999
    region_code: "us"
    region_name: "US"
    stun_listen_addr: "0.0.0.0:3478"
    automatically_add_embedded_derp_region: true
    private_key_path: /var/lib/headscale/private.key
  auto_update_enabled: true
  update_frequency: 4h

disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m
node_update_check_interval: 10s

database:
  type: sqlite3
  sqlite:
    path: /var/lib/headscale/hsdb.sqlite

acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: ""
tls_letsencrypt_hostname: ""
tls_letsencrypt_cache_dir: /var/lib/headscale/cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":http"

tls_cert_path: ""
tls_key_path: ""

log:
  format: text
  level: info

policy:
  mode: "database"

dns:
  override_local_dns: false
  nameservers:
    - 1.1.1.1
    - 1.0.0.1
  domains: ["example.com"]
  magic_dns: true
  base_domain: ts.example.com

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

oidc:
  only_start_if_oidc_is_available: true
  issuer: "https://login.microsoftonline.com/11111111-2222-4333-4444-555555555555/v2.0"
  client_id: "aaaaaaaa-bbbb-4ccc-dddd-eeeeeeeeeeee"
  client_secret: "<YourClientSecret>"
  expiry: 7d
  scope: ["openid", "profile", "email"]
  strip_email_domain: true
  extra_params:
    domain_hint: example.com
    prompt: select_account
  allowed_domains:
    - example.com
  # allowed_groups:
  #   - a1b2c3d4-aaaa-4bbb-cccc-a1b2c3d4e5f6

logtail:
  enabled: false

randomize_client_port: false
